### ISSUE TITLE
resetting blockchain for multibit wallet removed all of my receiving addresses, balance = 0 BTC now

### ISSUE THREAD

**Issue by samlasalle** [keepkey/multibit#757]
Hi,

I transferred about $500 to my multibit wallet but couldn't send it anywhere as the send button was greyed out. After taking too many hours to not even finish synchronizing I clicked to reset the blockchain, and then after reading online downloaded multibit classic 0.5.19. I have tried to open my wallet in each and synchronizing won't update the wallet. Multibit only shows four transactions from 2014, and one address. hundreds of addresses and transactions are missing.

I have tried exporting the private keys to send to a blockchain.info wallet however only the one private key is imported and that is showing 0 BTC in it. What can be done?

**Comment by jim618** [comment]
Old wallets take a while to synchronize now - your best bet is to find a fast network connection - MB/s is what you need. MultiBit connects to peers randomly at start up so if you have a slow peer then shut it down and restart it and try connecting to something faster.

Reseting the blockchain you probably did not need to do. That clears out the wallet and does a full resync which would have meant your sync was even longer.

Exporting your private keys is the fastest way to get access to your bitcoins.
Have a look in the unencrypted private key file. You should see one private key for each address that you have. There is a big comment in the header that explains the syntax.
You might want to import them one by one into blockchain.info to go through them systematically.

**Comment by samlasalle** [comment]
Hi Jim,
Thanks for getting back to me. I'm on a 13MB/s wireless connection right now. 
I have already tried exporting my private keys and the thing is that my multibit wallet now only shows one address, meaning that only one private key gets exported. The one remaining address has four transactions from 2014, but any address added after that isn't there anymore.

I have checked on the blockchain https://blockchain.info/address/1JdFnqh4oWgBNFaNnCao7CYaFoRKvJWGBs and my money is still at my address unused, how can I access it again?

Thanks,
Sam

**Comment by fbomb1** [comment]
Did you ever get this figured out? I have a similar problem and was hoping you might have found the answer.  Thanks

**Comment by samlasalle** [comment]
I haven't, and at this stage am giving up. It seems to me that the wallet key pairs were somehow deleted and are unrecoverable.

**Comment by kl8847** [comment]
hi, did you worked this out or it still the same problem?
contact me on innominatus010101 @ gmail.com
i might help you here

**Comment by kliyer** [comment]
Hi @samlasalle @fbomb1   sorry to hear you are facing issues with MultiBit. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
