### ISSUE TITLE
Cannot receive bitcoin funds in Bitcoin Core Wallet

### ISSUE THREAD

**Issue by wajj7** [keepkey/multibit#761]
I know very little about all of this, but thought it would be easy to make a deposit with Circle and to send it to Bitcoin Core as a wallet.
I originally sent money from Circle to Bitcoin Core Aug. 3rd. The bar at the bottom of Bitcoin Core read 7 years and some weeks. Later I was told that I had to let this run down to zero to be synced up. I left my computer on as I kept getting requests for more space on my computer. Eventually, after about 4 days, the bar went down to 1 year and some weeks. At this time, everything stopped. I have a very old computer and I assumed that was the problem. I started the process all over again at 7 years and some weeks. In the last three days, it has dwindled down to 2 years and 15 weeks, but once again is frozen. 

Someone recommended putting the wallet file into Blockchain to actually get the bitcoins I have not been able to access. I found the file, and dumped it into the window on Blockchain. I then typed the necessary info to ensure that I was not a robot. Then I got this prompt:

If this wallet is encrypted please enter the password below. Otherwise leave it blank. I left this blank, I have no idea what password I would have to enter. After I entered this info, nothing happens. No new wallet is opened and when I did open a new wallet with them, I don't see any of these bitcoins in the wallet.

ANY HELP???? Please!?

Thanks, and thanks for your patience with my lack of knowledge about all of this.

**Comment by bgok** [comment]
I'm sorry to hear that you are having such a difficult time. Unfortunately, we are not able to provide support for bitcoin core. My best suggestion is to post your issue to https://www.reddit.com/r/btc/ or https://www.reddit.com/r/bitcoin/. If you need assistance with a KeepKey product, please visit our support desk at https://keepkey.freshdesk.com/support/solutions.
