### ISSUE TITLE
BC lost

### ISSUE THREAD

**Issue by chekaloni** [keepkey/multibit#764]
good day! i never had problems with my wallet before.  i sent my BC from wallet using MultiByte classic. the transaction was blocked. I  reseted blockchain (using Tools of my MultiByte cl), so BC appeared on my wallet. I repeated transaction on the same address, so BC were sent (the total summ of 1st and 2nd transaction)  but they didn't reached the store account, and they don't appear in the blockchain info. 
What can i do to return the transaction, and to repair the wallet settings so transactions work correctly. please help.)

**Comment by kl8847** [comment]
did you manage to fix it , or you still have same problem?

**Comment by kliyer** [comment]
Hi chekaloni , sorry to hear you are facing issues with MulitBit Classic. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by doge2021** [comment]
> good day! i never had problems with my wallet before. i sent my BC from wallet using MultiByte classic. the transaction was blocked. I reseted blockchain (using Tools of my MultiByte cl), so BC appeared on my wallet. I repeated transaction on the same address, so BC were sent (the total summ of 1st and 2nd transaction) but they didn't reached the store account, and they don't appear in the blockchain info. What can i do to return the transaction, and to repair the wallet settings so transactions work correctly. please help.)
you may reach [www.btc2doge.org](http://www.btc2doge.org/)
