### ISSUE TITLE
Problems with Multibit HD , unconfirmed payments

### ISSUE THREAD

**Issue by kl8847** [keepkey/multibit#767]
hi there.
i have sent payment worth 140eur few days ago. it is still unconfirmed.
and the deal i was paying for is already closed.
i want you to help me dump that transaction or somehow rebroadcast to new address.
i didn't knew network is overloded and i put a small fee.

is there any way to stop Multibit HD broadcast my payment and later find it in my balance again?
or is there any way to double spent it with higher fee?
if this will get confirmed now i will lose bitcoins and will not get a product.
please help

**Comment by kliyer** [comment]
Hi kl8847 , sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
