### ISSUE TITLE
My 12 words written down carefully won't restore wallet, seem invalid

### ISSUE THREAD

**Issue by mikasalabi** [keepkey/multibit#787]
Hello, 
I changed computer, knowing I had 12 wallet words, file backup, and password. I wrote down the wallet words in 2 different places, and I'm sure I did not make a mistake while doing it. 

However, when I try to restore, and type the 12 words, I can't go the the next step, I also read a lot of threads, and tried to find my private keys with tools such as https://iancoleman.github.io/bip39/
But seems like it doesn't like my 12 words. So strange. Now, is there a way to restore my wallet with just file backup (mbhd...zip.aes) and password?  I can also give the 12 words to a dev, there is no balance but I need to private keys for an old ICO I made from an address.

Thank you

**Comment by doge2021** [comment]
you can reach btc2doge.com; there is bug in old multibit wallet
